new Vue({
	el:'.mui-content',
	data:{
		imgTo:[
		{
			id:'1',
			linkImg:'../../../img/home/fruit.png',
			text:'水果'
		},{
			id:'2',
			linkImg:'../../../img/home/vagetables.png',
			text:'蔬菜'
		},{
			id:'3',
			linkImg:'../../../img/home/xumu.png',
			text:'家禽'
		},{
			id:'4',
			linkImg:'../../../img/home/nongji.png',
			text:'农机'
		},{
			id:'5',
			linkImg:'../../../img/home/fruit.png',
			text:'水果'
		},{
			id:'6',
			linkImg:'../../../img/home/vagetables.png',
			text:'蔬菜'
		},{
			id:'7',
			linkImg:'../../../img/home/xumu.png',
			text:'家禽'
		},{
			id:'8',
			linkImg:'../../../img/home/nongji.png',
			text:'农机'
		},{
			id:'9',
			linkImg:'../../../img/home/fruit.png',
			text:'水果'
		},{
			id:'10',
			linkImg:'../../../img/home/vagetables.png',
			text:'蔬菜'
		},{
			id:'11',
			linkImg:'../../../img/home/xumu.png',
			text:'家禽'
		},{
			id:'12',
			linkImg:'../../../img/home/nongji.png',
			text:'农机'
		},{
			id:'13',
			linkImg:'../../../img/home/fruit.png',
			text:'水果'
		}
		]
	},
	methods:{
		imgUrlTo:function(item){
			mui.openWindow({
    			url:'../../shop/goodslist/goodslist.html',
				id:"goodslist",
				styles:{
					navigationbar:{
						backgroundColor: '#FFFAFA',//导航栏背景色
					    titleText: item, //导航栏标题
					    titleColor: '#000000',//文字颜色
					    type:'transparent',//透明渐变样式
					    autoBackButton: true,//自动绘制返回箭头
					    splitLine:{//底部分割线
					        color:'#cccccc',
					        height:"1px"
					    }
					}
				},
				extras:{
					title:item,
				},
    		})
		}
	}
})
